name: Build Singularity Container

on:
  push:
    paths:
      - 'dummy.def'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: quay.io/singularity/singularity:v4.3.1
      options: --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build SIF container
        run: |
          singularity build output.sif dummy.def

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sif-container
          path: output.sif

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: sif-container
          path: ./retrieved

      - name: Show workflow environment
        run: |
          cat /proc/cpuinfo
          df -h
          
